<a href="https://colab.research.google.com/github/SANAD343/Numpy/blob/main/Python_NumPy_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# Numpy - Array Manipulation.

In [2]:
arr = np.random.randint(1,10 , (4,4))
arr

array([[3, 1, 5, 4],
       [2, 8, 7, 3],
       [3, 8, 8, 5],
       [9, 6, 1, 5]])

In [3]:
arr.reshape(8,2)

array([[3, 1],
       [5, 4],
       [2, 8],
       [7, 3],
       [3, 8],
       [8, 5],
       [9, 6],
       [1, 5]])

In [4]:
arr

array([[3, 1, 5, 4],
       [2, 8, 7, 3],
       [3, 8, 8, 5],
       [9, 6, 1, 5]])

In [5]:
arr.T

array([[3, 2, 3, 9],
       [1, 8, 8, 6],
       [5, 7, 8, 1],
       [4, 3, 5, 5]])

In [6]:
arr.flatten()

array([3, 1, 5, 4, 2, 8, 7, 3, 3, 8, 8, 5, 9, 6, 1, 5])

In [7]:
arr

array([[3, 1, 5, 4],
       [2, 8, 7, 3],
       [3, 8, 8, 5],
       [9, 6, 1, 5]])

In [8]:
np.expand_dims(arr,axis=1)

array([[[3, 1, 5, 4]],

       [[2, 8, 7, 3]],

       [[3, 8, 8, 5]],

       [[9, 6, 1, 5]]])

In [9]:
np.expand_dims(arr,axis=0)

array([[[3, 1, 5, 4],
        [2, 8, 7, 3],
        [3, 8, 8, 5],
        [9, 6, 1, 5]]])

In [10]:
data = np.array([[1] , [2] , [3]])
print(np.squeeze(data))

[1 2 3]


In [11]:
print(np.repeat(data,4))

[1 1 1 1 2 2 2 2 3 3 3 3]


In [12]:
print(np.roll(data,2))

[[2]
 [3]
 [1]]


In [13]:
print(np.diag(np.array([1,2,3,4])))

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


# Numpy - Binary Operators

In [14]:
arr1 = np.random.randint(1,10 , (3,4))
arr2 = np.random.randint(1,10 , (3,4))

In [15]:
arr1

array([[9, 7, 9, 5],
       [9, 2, 3, 9],
       [6, 7, 4, 1]])

In [16]:
arr2

array([[9, 2, 1, 2],
       [9, 2, 6, 4],
       [2, 3, 2, 4]])

In [17]:
arr1+arr2

array([[18,  9, 10,  7],
       [18,  4,  9, 13],
       [ 8, 10,  6,  5]])

In [18]:
arr1*arr2

array([[81, 14,  9, 10],
       [81,  4, 18, 36],
       [12, 21,  8,  4]])

In [19]:
arr1/arr2

array([[1.        , 3.5       , 9.        , 2.5       ],
       [1.        , 1.        , 0.5       , 2.25      ],
       [3.        , 2.33333333, 2.        , 0.25      ]])

In [20]:
arr1-arr2

array([[ 0,  5,  8,  3],
       [ 0,  0, -3,  5],
       [ 4,  4,  2, -3]])

In [21]:
arr1**arr2

array([[387420489,        49,         9,        25],
       [387420489,         4,       729,      6561],
       [       36,       343,        16,         1]])

In [22]:
~arr1

array([[-10,  -8, -10,  -6],
       [-10,  -3,  -4, -10],
       [ -7,  -8,  -5,  -2]])

In [23]:
arr1

array([[9, 7, 9, 5],
       [9, 2, 3, 9],
       [6, 7, 4, 1]])

In [24]:
arr1>arr2

array([[False,  True,  True,  True],
       [False, False, False,  True],
       [ True,  True,  True, False]])

# Numpy - String Functions

In [26]:
arr = np.array(["sanad" , "kumar","Singh"])

In [27]:
arr

array(['sanad', 'kumar', 'Singh'], dtype='<U5')

In [28]:
np.char.upper(arr)

array(['SANAD', 'KUMAR', 'SINGH'], dtype='<U5')

In [29]:
np.char.capitalize(arr)

array(['Sanad', 'Kumar', 'Singh'], dtype='<U5')

In [30]:
np.char.title(arr)

array(['Sanad', 'Kumar', 'Singh'], dtype='<U5')

# Numpy - Mathematical Functions.

In [31]:
arr1

array([[9, 7, 9, 5],
       [9, 2, 3, 9],
       [6, 7, 4, 1]])

In [32]:
np.sin(arr1)

array([[ 0.41211849,  0.6569866 ,  0.41211849, -0.95892427],
       [ 0.41211849,  0.90929743,  0.14112001,  0.41211849],
       [-0.2794155 ,  0.6569866 , -0.7568025 ,  0.84147098]])

In [33]:
np.cos(arr1)

array([[-0.91113026,  0.75390225, -0.91113026,  0.28366219],
       [-0.91113026, -0.41614684, -0.9899925 , -0.91113026],
       [ 0.96017029,  0.75390225, -0.65364362,  0.54030231]])

In [34]:
np.tan(arr1)

array([[-0.45231566,  0.87144798, -0.45231566, -3.38051501],
       [-0.45231566, -2.18503986, -0.14254654, -0.45231566],
       [-0.29100619,  0.87144798,  1.15782128,  1.55740772]])

In [35]:
np.log10(arr1)

array([[0.95424251, 0.84509804, 0.95424251, 0.69897   ],
       [0.95424251, 0.30103   , 0.47712125, 0.95424251],
       [0.77815125, 0.84509804, 0.60205999, 0.        ]])

In [36]:
np.exp(arr1)

array([[8.10308393e+03, 1.09663316e+03, 8.10308393e+03, 1.48413159e+02],
       [8.10308393e+03, 7.38905610e+00, 2.00855369e+01, 8.10308393e+03],
       [4.03428793e+02, 1.09663316e+03, 5.45981500e+01, 2.71828183e+00]])

In [37]:
np.power(arr1,2)

array([[81, 49, 81, 25],
       [81,  4,  9, 81],
       [36, 49, 16,  1]])

In [38]:
np.mean(arr1)

5.916666666666667

In [39]:
np.median(arr1)


6.5

In [40]:
np.std(arr1)

2.782634642844

In [41]:
np.var(arr1)

7.743055555555556

In [42]:
np.min(arr1)

1

In [43]:
np.max(arr1)

9

# Numpy - Arithmetic Operations.

In [44]:
arr1

array([[9, 7, 9, 5],
       [9, 2, 3, 9],
       [6, 7, 4, 1]])

In [45]:
arr2

array([[9, 2, 1, 2],
       [9, 2, 6, 4],
       [2, 3, 2, 4]])

In [46]:
arr1-arr2

array([[ 0,  5,  8,  3],
       [ 0,  0, -3,  5],
       [ 4,  4,  2, -3]])

In [47]:
np.subtract(arr1,arr2)

array([[ 0,  5,  8,  3],
       [ 0,  0, -3,  5],
       [ 4,  4,  2, -3]])

In [48]:
np.multiply(arr1,arr2)

array([[81, 14,  9, 10],
       [81,  4, 18, 36],
       [12, 21,  8,  4]])

In [49]:
np.mod(arr1,arr2)

array([[0, 1, 0, 1],
       [0, 0, 3, 1],
       [0, 1, 0, 1]])

In [50]:
np.power(arr1,arr2)

array([[387420489,        49,         9,        25],
       [387420489,         4,       729,      6561],
       [       36,       343,        16,         1]])

In [51]:
np.sqrt(arr1)

array([[3.        , 2.64575131, 3.        , 2.23606798],
       [3.        , 1.41421356, 1.73205081, 3.        ],
       [2.44948974, 2.64575131, 2.        , 1.        ]])

# Numpy - Statistical Functions.

In [52]:
arr1

array([[9, 7, 9, 5],
       [9, 2, 3, 9],
       [6, 7, 4, 1]])

In [53]:
np.mean(arr1)

5.916666666666667

In [54]:
np.std(arr1)

2.782634642844

In [55]:
np.median(arr1)

6.5

#  Sort, Search & Counting Functions.

In [56]:
import numpy as np

In [57]:
arr = np.array([4,2,8,5,3,9,12,56])

In [58]:
arr

array([ 4,  2,  8,  5,  3,  9, 12, 56])

In [59]:
np.sort(arr)

array([ 2,  3,  4,  5,  8,  9, 12, 56])

In [60]:
np.searchsorted(arr,6)

5

In [61]:
arr1 = np.array([0,324,645,65,6,6,0,0,0,234])

In [62]:
np.count_nonzero(arr1)

6

In [63]:
np.where(arr1 > 0 )

(array([1, 2, 3, 4, 5, 9]),)

In [64]:
np.extract(arr1 >2,arr1)

array([324, 645,  65,   6,   6, 234])

In [65]:
# Numpy - Byte Swapping

In [66]:
arr1

array([  0, 324, 645,  65,   6,   6,   0,   0,   0, 234])

In [67]:
arr.byteswap(True)

array([ 288230376151711744,  144115188075855872,  576460752303423488,
        360287970189639680,  216172782113783808,  648518346341351424,
        864691128455135232, 4035225266123964416])

In [68]:
arr

array([ 288230376151711744,  144115188075855872,  576460752303423488,
        360287970189639680,  216172782113783808,  648518346341351424,
        864691128455135232, 4035225266123964416])

# Numpy - Copies &Views.

In [69]:
arr1

array([  0, 324, 645,  65,   6,   6,   0,   0,   0, 234])

In [70]:
a = np.copy(arr1)

In [71]:
b = arr1.view()

In [72]:
b=arr1

In [73]:
b

array([  0, 324, 645,  65,   6,   6,   0,   0,   0, 234])

In [74]:
b[0]=234

In [75]:
b

array([234, 324, 645,  65,   6,   6,   0,   0,   0, 234])

In [76]:
arr1

array([234, 324, 645,  65,   6,   6,   0,   0,   0, 234])

# Numpy - Matrix Library.

In [77]:
import numpy.matlib as nm

In [78]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [79]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [80]:
nm.eye(4)

matrix([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

# Numpy - Linear Algebra

In [81]:
arr1 = np.random.randint([[2,3] , [4,5]])
arr2 = np.random.randint([[5,3] , [2,5]])

In [83]:
print(arr1)
arr2

[[1 2]
 [0 4]]


array([[0, 1],
       [0, 1]])

In [84]:
np.dot(arr1,arr2)

array([[0, 3],
       [0, 4]])

In [85]:
arr1@arr2

array([[0, 3],
       [0, 4]])