<a href="https://colab.research.google.com/github/SANAD343/Numpy/blob/main/Python_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
l=[1,2,3,4,5]

In [3]:
arr=np.array(l)

In [4]:
type(arr)

numpy.ndarray

In [5]:
np.asarray(l)

array([1, 2, 3, 4, 5])

In [6]:
arr1 = np.array([[1,2,3] , [2,3,4]])

In [7]:
arr.ndim

1

In [8]:
arr1.ndim

2

In [9]:
arr

array([1, 2, 3, 4, 5])

In [10]:
arr1

array([[1, 2, 3],
       [2, 3, 4]])

In [11]:
mat=np.matrix(1)

In [14]:
np.asanyarray(mat)

matrix([[1]])

In [13]:
arr

array([1, 2, 3, 4, 5])

In [15]:
a=arr

In [16]:
a

array([1, 2, 3, 4, 5])

In [17]:
arr

array([1, 2, 3, 4, 5])

In [18]:
arr[0]=130
arr

array([130,   2,   3,   4,   5])

In [19]:
a

array([130,   2,   3,   4,   5])

In [20]:
b=np.copy(arr)  #copy array to new array
b

array([130,   2,   3,   4,   5])

In [21]:
b[0]=234
b

array([234,   2,   3,   4,   5])

In [22]:
arr

array([130,   2,   3,   4,   5])

In [23]:
np.fromfunction(lambda i,j : i==j , (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [24]:
np.fromfunction(lambda i,j : i*j , (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [25]:
list(i*i for i in range(5))

[0, 1, 4, 9, 16]

In [26]:
iterable = (i*i for i in range(5))

In [27]:
np.fromiter(iterable, float)

array([ 0.,  1.,  4.,  9., 16.])

In [28]:
np.fromstring('23 45 56',sep  = ' ' )

array([23., 45., 56.])

In [29]:
np.fromstring('23,45,56',sep  = ',' )

array([23., 45., 56.])

In [30]:
arr

array([130,   2,   3,   4,   5])

In [31]:
arr1

array([[1, 2, 3],
       [2, 3, 4]])

In [32]:
arr.ndim

1

In [33]:
arr1.ndim

2

In [34]:
print(arr.size)
print(arr1.size)
print(arr.shape)
print(arr1.shape)

5
6
(5,)
(2, 3)


In [36]:
print(arr1)
print(arr.dtype)
print(arr1.dtype)

[[1 2 3]
 [2 3 4]]
int64
int64


# Range Function

In [37]:
list(range(5))

[0, 1, 2, 3, 4]

In [38]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [39]:
list(range(0.4,10.4)) # will not work as the range can't be defined in float values

TypeError: 'float' object cannot be interpreted as an integer

In [40]:
list(np.arange(.4 , 10.4 , 0.2)) #start from 0.1 till 10.4 with step of 0.2

[0.4,
 0.6000000000000001,
 0.8000000000000002,
 1.0000000000000002,
 1.2000000000000002,
 1.4000000000000004,
 1.6000000000000005,
 1.8000000000000003,
 2.0000000000000004,
 2.2000000000000006,
 2.400000000000001,
 2.6000000000000005,
 2.8000000000000007,
 3.000000000000001,
 3.2000000000000006,
 3.400000000000001,
 3.600000000000001,
 3.800000000000001,
 4.000000000000002,
 4.200000000000001,
 4.400000000000002,
 4.600000000000001,
 4.800000000000002,
 5.000000000000002,
 5.200000000000002,
 5.400000000000002,
 5.600000000000002,
 5.8000000000000025,
 6.000000000000002,
 6.200000000000002,
 6.400000000000002,
 6.600000000000002,
 6.8000000000000025,
 7.000000000000003,
 7.200000000000003,
 7.400000000000003,
 7.600000000000003,
 7.8000000000000025,
 8.000000000000002,
 8.200000000000003,
 8.400000000000004,
 8.600000000000003,
 8.800000000000002,
 9.000000000000004,
 9.200000000000003,
 9.400000000000004,
 9.600000000000003,
 9.800000000000004,
 10.000000000000004,
 10.20000000000000

In [42]:
np.linspace(1, 5, 20)  # pull 20 values  within linspance from 1 to 5

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [43]:
np.logspace(1,5 , 10, base=2)

array([ 2.        ,  2.72158   ,  3.70349885,  5.0396842 ,  6.85795186,
        9.33223232, 12.69920842, 17.28095582, 23.51575188, 32.        ])

In [44]:
np.zeros(5) #1*5 matrix with 0es

array([0., 0., 0., 0., 0.])

In [45]:
np.zeros((3,4)) #3*4 matrix with 0es

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [46]:
np.zeros((3,4,2)) #creating 3 different matrix 4*2 matrix

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [47]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [48]:
arr = np.ones((3,4))

In [49]:
arr


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [50]:
arr+5

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [51]:
arr*4

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [52]:
np.empty((3,4))

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [53]:
arr1 = np.eye(5)

In [54]:
arr1

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [55]:
import pandas as pd

In [56]:
pd.DataFrame(arr1)

0    1    2    3    4
0  1.0  0.0  0.0  0.0  0.0
1  0.0  1.0  0.0  0.0  0.0
2  0.0  0.0  1.0  0.0  0.0
3  0.0  0.0  0.0  1.0  0.0
4  0.0  0.0  0.0  0.0  1.0

In [57]:
np.random.rand(2,3)

array([[0.48008281, 0.28242471, 0.84600703],
       [0.8073157 , 0.08897946, 0.14714346]])

In [58]:
np.random.randn(2,3)

array([[ 1.28926922, -0.92080915,  2.35535705],
       [ 0.30958976, -0.57861936,  0.52388505]])

In [59]:
arr2 = np.random.randint(1,5 , (3,4))

In [60]:
arr2

array([[4, 1, 3, 4],
       [2, 4, 4, 3],
       [3, 2, 1, 2]])

In [61]:
print(arr2.size)
print(arr2.shape)

12
(3, 4)


In [62]:
print(arr2.reshape(6,2))

[[4 1]
 [3 4]
 [2 4]
 [4 3]
 [3 2]
 [1 2]]


In [63]:
print(arr2.reshape(2,6))

[[4 1 3 4 2 4]
 [4 3 3 2 1 2]]


In [64]:
print(arr2.reshape(4,3))

[[4 1 3]
 [4 2 4]
 [4 3 3]
 [2 1 2]]


In [65]:
print(arr2.reshape(4,-1))

[[4 1 3]
 [4 2 4]
 [4 3 3]
 [2 1 2]]


In [66]:
arr2.reshape(4,-1432453453)

array([[4, 1, 3],
       [4, 2, 4],
       [4, 3, 3],
       [2, 1, 2]])

In [67]:
arr2.reshape(2,2,3,1,1,1)

array([[[[[[4]]],


         [[[1]]],


         [[[3]]]],



        [[[[4]]],


         [[[2]]],


         [[[4]]]]],




       [[[[[4]]],


         [[[3]]],


         [[[3]]]],



        [[[[2]]],


         [[[1]]],


         [[[2]]]]]])

In [68]:
arr1 = np.random.randint(1,10 , (5,6))
arr1

array([[5, 8, 3, 8, 6, 5],
       [9, 3, 9, 5, 7, 5],
       [9, 5, 3, 2, 7, 1],
       [5, 8, 6, 4, 5, 8],
       [5, 8, 2, 1, 5, 2]])

In [69]:
arr1>8

array([[False, False, False, False, False, False],
       [ True, False,  True, False, False, False],
       [ True, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False]])

In [70]:
arr1[arr1 >8]

array([9, 9, 9])

In [71]:
arr1

array([[5, 8, 3, 8, 6, 5],
       [9, 3, 9, 5, 7, 5],
       [9, 5, 3, 2, 7, 1],
       [5, 8, 6, 4, 5, 8],
       [5, 8, 2, 1, 5, 2]])

In [72]:
arr1[0,[0,1]]

array([5, 8])

In [73]:
arr1[2:4,[2,3]]

array([[3, 2],
       [6, 4]])

In [74]:
arr1 = np.random.randint(1,3 , (3,3))
arr2 = np.random.randint(1,3 , (3,3))

In [75]:
arr1

array([[1, 1, 2],
       [2, 1, 2],
       [2, 2, 1]])

In [76]:
arr1

array([[1, 1, 2],
       [2, 1, 2],
       [2, 2, 1]])

In [77]:
arr2

array([[2, 2, 2],
       [1, 1, 1],
       [1, 2, 2]])

In [78]:
arr1+arr2

array([[3, 3, 4],
       [3, 2, 3],
       [3, 4, 3]])

In [79]:
arr1-arr2

array([[-1, -1,  0],
       [ 1,  0,  1],
       [ 1,  0, -1]])

In [80]:
arr1*arr2

array([[2, 2, 4],
       [2, 1, 2],
       [2, 4, 2]])

In [81]:
arr1

array([[1, 1, 2],
       [2, 1, 2],
       [2, 2, 1]])

In [82]:
arr2

array([[2, 2, 2],
       [1, 1, 1],
       [1, 2, 2]])

In [83]:
arr1@arr2

array([[5, 7, 7],
       [7, 9, 9],
       [7, 8, 8]])

In [84]:
arr1/arr2

array([[0.5, 0.5, 1. ],
       [2. , 1. , 2. ],
       [2. , 1. , 0.5]])

In [85]:
arr1/0

<ipython-input-85-2e1dc0d9289f>:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [86]:
#Numpy – Broadcasting.

In [87]:
arr = np.zeros((3,4))

In [88]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [89]:
arr+5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [90]:
a = np.array([1,2,3,4])
arr+a

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [91]:
b = np.array([[3,4,5]])
arr1 = arr+b.T

In [92]:
b.T

array([[3],
       [4],
       [5]])

In [93]:
arr1

array([[3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.]])

In [94]:
np.sqrt(arr1)

array([[1.73205081, 1.73205081, 1.73205081, 1.73205081],
       [2.        , 2.        , 2.        , 2.        ],
       [2.23606798, 2.23606798, 2.23606798, 2.23606798]])

In [95]:
np.log10(arr1)

array([[0.47712125, 0.47712125, 0.47712125, 0.47712125],
       [0.60205999, 0.60205999, 0.60205999, 0.60205999],
       [0.69897   , 0.69897   , 0.69897   , 0.69897   ]])

In [96]:
np.exp(arr1)

array([[ 20.08553692,  20.08553692,  20.08553692,  20.08553692],
       [ 54.59815003,  54.59815003,  54.59815003,  54.59815003],
       [148.4131591 , 148.4131591 , 148.4131591 , 148.4131591 ]])

In [97]:
np.min(arr1)

3.0

In [98]:
np.max(arr1)

5.0